// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' ;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVOKLiVvlygl6i3jrnkE5mjs4FsD--Ngk',
    appId: '1:369786801802:web:51b1d2da704ba8a0432773',
    messagingSenderId: '369786801802',
    projectId: 'spidermandelivery',
    authDomain: 'spidermandelivery.firebaseapp.com',
    storageBucket: 'spidermandelivery.firebasestorage.app',
    measurementId: 'G-GT5DNLNG3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ1u7ESSbMGRnD0AUfTRTGx8r2AqhqkAQ',
    appId: '1:369786801802:android:4d0a7b81b8db9107432773',
    messagingSenderId: '369786801802',
    projectId: 'spidermandelivery',
    storageBucket: 'spidermandelivery.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhhJOyX-UHVhNtMHdm2YpwJDn5KnLBzDY',
    appId: '1:369786801802:ios:156cf4f6ad2a3ccb432773',
    messagingSenderId: '369786801802',
    projectId: 'spidermandelivery',
    storageBucket: 'spidermandelivery.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhhJOyX-UHVhNtMHdm2YpwJDn5KnLBzDY',
    appId: '1:369786801802:ios:156cf4f6ad2a3ccb432773',
    messagingSenderId: '369786801802',
    projectId: 'spidermandelivery',
    storageBucket: 'spidermandelivery.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVOKLiVvlygl6i3jrnkE5mjs4FsD--Ngk',
    appId: '1:369786801802:web:341bd2e4ce87a1a2432773',
    messagingSenderId: '369786801802',
    projectId: 'spidermandelivery',
    authDomain: 'spidermandelivery.firebaseapp.com',
    storageBucket: 'spidermandelivery.firebasestorage.app',
    measurementId: 'G-LSBJBV4MZ1',
  );
}
